apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mssql
  newName: mcr.microsoft.com/mssql/server
  newTag: 2017-CU21-ubuntu-16.04
- name: solr
  newName: sitecore-xp-sxa-solr
  newTag: 9.3.0-linux

resources:
  - mssql.yaml
  - solr.yaml
