apiVersion: v1
kind: ConfigMap
metadata:
  name: sitecore-schema-populate-script
data:
  populate-script.ps1: |
    $sitecoreUrl = "http://solr:8983/sitecore/admin/PopulateManagedSchema.aspx"
    $payload = @{
        configset = "sitecore"
        indexes = @("sitecore_sxa_master_index", "sitecore_sxa_web_index")
    } | ConvertTo-Json
    Invoke-RestMethod -Uri $sitecoreUrl -Method Post -Body $payload -ContentType "application/json"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: solr-collection-init
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: solr-collection-init
        image: mcr.microsoft.com/powershell:latest
        command: ["pwsh", "-File", "/scripts/populate-script.ps1"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: sitecore-schema-populate-script
          